# Generated by Django 5.1.7 on 2025-04-02 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='poisition',
            field=models.ForeignKey(default='Default position', on_delete=django.db.models.deletion.CASCADE, to='api.position'),
        ),
    ]
