# Generated by Django 5.1.7 on 2025-04-02 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vacancy_poisition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='poisition',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.position'),
        ),
    ]
